# author: jokhan
# problem: two sum

CC = g++
CFLAGS = -ggdb3 -std=c++11
all = main

$(all).out: $(all).cpp
	$(CC) $(CFLAGS) -o $@ $<
clean:
	@echo "Cleanning project"
	rm $(all).out
	@echo "Clean completed"
.PhONY: clean
